<<<<<<< HEAD
# Generated by Django 3.1.2 on 2020-11-09 02:39
=======
# Generated by Django 3.1.2 on 2020-11-06 02:47
>>>>>>> 2dace9ae4acc70a81338c6f569ca6e7930c506b5

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0002_auto_20201105_2249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
