# Generated by Django 3.1.2 on 2020-11-09 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0002_auto_20201105_2249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
