# Generated by Django 3.1.2 on 2020-11-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProyectowebApp', '0003_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nickname', models.CharField(max_length=200)),
                ('Correo', models.CharField(max_length=200)),
                ('asunto', models.CharField(max_length=200)),
                ('Comentario', models.CharField(max_length=1000)),
            ],
        ),
    ]
