# Generated by Django 3.1.2 on 2020-11-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(upload_to='equipos'),
        ),
    ]
